### ISSUE TITLE
[Enhancement] Iframe search website in Obsidian

### ISSUE THREAD

**Issue by Quorafind** [HEmile/obsidian-search-on-internet#1]
Obsidian allows us to use iframe to display content of website in Obsidian.

So is it possible to have a context menu that allows you to search content and then create new pane near notes?

for example:

<iframe src="https://www.google.com/search?q=obsidian" style="position:absolute; top:0; left:0; width:100%; border:none;  height:100%;">

https://user-images.githubusercontent.com/13215013/104869295-a8f13c80-5980-11eb-96e6-0f9f9cca4817.mp4

**Comment by HEmile** [comment]
Interesting idea! I really like the idea of selecting some text and then executing the search based on that.
I don't think I'll do the iframe search, though. I think I heard the developers of Obsidian talk about Electron not being a great browser to do general 'website browsing' in.

**Comment by Quorafind** [comment]
@HEmile 🤣That's alright. Just a small idae to enhance the plugin. It will be more useful if people can config which website to search.

**Comment by HEmile** [comment]
I looked into this a bit more. It turns out that it's actually safe to embed websites in an iframe! There's a caveat though: Many sites will block being embedded in an iframe, like Google.

**Comment by Quorafind** [comment]
> I looked into this a bit more. It turns out that it's actually safe to embed websites in an iframe! There's a caveat though: Many sites will block being embedded in an iframe, like Google.

Thanks for still looking into this! I should tell you why I wanted to use iframe before:

Don't need to open a browser to search things but just in Obsidian, which is good for us to focus on Obsidian. For example, it would be nice for me to search WORD when I read books in Obsidian.

A Use Case:
I used wikidictionary to search WORD and then iframe it in Obsidian.

And then, I do find google or duckduckgo cannot be embedded into a iframe. But there are other search engine like bing.com allows us to embed it in iframe. 

Suggestion:
Turnning it an option to alllows people just open a new iframe rather than open a browser would be nice. 😆

**Comment by HEmile** [comment]
Good news: With the new Obsidian plugin, all iframes are supported! The new update of the plugin will open searches in iframes :)
