### ISSUE TITLE
Embed other search engines

### ISSUE THREAD

**Issue by benytzlich** [HEmile/obsidian-search-on-internet#11]
I tried the syntax for duckduckgo.com and startpage.com -> it works

but if try iframe it doesnt load... Am  I missing something, or does duckduckgo ++ doesnt allow embedded search?

**Comment by HEmile** [comment]
Duckduckgo indeed does not allow embedding through iframes. This isn't something I can solve, it's the limitation of iframes. At least, as far as my understanding goes.

**Comment by HEmile** [comment]
Hi, good news: Obsidian changed how they handle IFrames, and now are able to handle duckduckgo :)
