### ISSUE TITLE
Context menu in editor is broken in Obsidian versions above v0.11.9

### ISSUE THREAD

**Issue by HEmile** [HEmile/obsidian-search-on-internet#14]
Obsidian changed the Codemirror instance and now uses a wrapper around it to ensure compatibility. This broke the context menu.

**Comment by luckman212** [comment]
@HEmile is it still the case with 0.12.4 ?

**Comment by AngelusDomini** [comment]
Maybe you could get this to work again with phibr0's [Extended Context Menu plugin](https://github.com/phibr0/obsidian-extended-context-menu)?

**Comment by HEmile** [comment]
Yes, that's the plan, in fact I already have a version of this ready. I'll submit it soon.
