### ISSUE TITLE
Feature Request: command and right-click option to replace currently selected text with a markdown link of the first hit for that search on the given provider

### ISSUE THREAD

**Issue by thomasvs** [HEmile/obsidian-search-on-internet#27]
Use case: I write some text, like "Roam, Notion, Evernote, Obsidian, LogSeq"

I want to quickly select each word and hyperlink it to the top hit on google which most likely will be the homepage for that tool.

Second use case: I write a common term, like "Personal Knowledge Management".

I want to select those three words, and use a command or right-click option to replace it with the markdown wikipedia link.

**Comment by HEmile** [comment]
Interesting idea, but way out of scope for this plugin. It'd require interacting with eg the Google API which is notoriously hard to do (especially not for free). If you know of any search provider that offers this option for free (do check the terms of service!) and are willing to implement this, feel free to submit a PR and reopen this issue.

**Comment by thomasvs** [comment]
Hm, interesting that getting a search result is out of scope for this plugin.

Wouldn't it be possible to simply scrape the resulting page the plugin currently opens? Why would you have to go through the google API?

**Comment by HEmile** [comment]
I'm pretty sure that's against the Google ToS. Also it's not that easy, haha
