### ISSUE TITLE
[Enhancement] Right Click On [[Blabla|TEXTEXT]] To Search TEXTTEXT

### ISSUE THREAD

**Issue by Quorafind** [HEmile/obsidian-search-on-internet#4]
I do not know if it is possible to search stuff behind the real file name, like:

[[Blabla`|`TEXTTEXT]] and the `TEXTTEXT` is the true text I used on the document.

**Comment by HEmile** [comment]
Hmm, yeah that might be confusing. If you select the text manually, you should be able to do it (like in this demo ![](https://raw.githubusercontent.com/HEmile/obsidian-search-on-internet/master/resources/modal_demo.gif).

Is that enough? Or would you rather have it on a file name?

**Comment by HEmile** [comment]
Right-clicking selected text now pull up a context menu to search (v0.3.0)
