### ISSUE TITLE
Adding other search sites not working.. or am Imissing something

### ISSUE THREAD

**Issue by osman1963** [HEmile/obsidian-search-on-internet#7]
Great plugin.. thanks a bunch
It works fine. When I higlight any word and right click and search it works fine. and get me the results.
I thought it was for searching the title of then note only, but it seems it searches whatever word I'm clicking when I chose search google or search wikipeda
I tried, however, to add other search sites (mostly dictionaries online) but it didn't work
I used {{title}},, {{0}}, {{q}} without the {} and with just single pair not double.. ntohing worked. 
I'm not a programmer, so forgive me if there is another way to add other sites that I don't know of
Thanks again for the great work and thanks in advance for your help
Have a lovley day !

**Comment by HEmile** [comment]
Hi there! The only template you can use is {{query}}. The {{query}} template will be filled in contextually with either the title or the selected text. What site are you trying to add?

**Comment by osman1963** [comment]
Thanks for your prompt reply!

I tried with McMillan dictionary. Here is how I added it
https://www.macmillandictionary.com/dictionary/british/search?q={{query}}

The result in the address bar of the browser is
https://www.macmillandictionary.com/dictionary/british/search_1

I tried also with Larousse
https://www.larousse.fr/dictionnaires/espagnol-francais/{{query}}
and here the response in the browser
https://www.larousse.fr/dictionnaires/espagnol-francais/%7B%7Bquery%7D%7D

Thanks again

**Comment by HEmile** [comment]
My apologies, looks like I didn't update the settings properly in the last update. It should actually be {{title}}, not {{query}}, but I'll also make {{query}} possible in the next version to make it clearer. 

On the first site, what works for me is https://www.macmillandictionary.com/spellcheck/british/?q={{title}} However, it 

On the second site, https://www.larousse.fr/dictionnaires/espagnol-francais/{{title}} seems to work?

However, both don't seem to work well with iframes.

**Comment by osman1963** [comment]
Bingo! they both work fine.. thanks a million man. I can live without
iframes.. and no worries regarding the settings update.. it is already a
great plugin as it is .
Thanks again

**Comment by HEmile** [comment]
Thank you! Glad to help :)

**Comment by HEmile** [comment]
Hi there, the latest Obsidian insider release changed how it handles iframes, and it looks like the translation website now works with it!

**Comment by osman1963** [comment]
Wow.. that's great news! Thanks for pointing that out, it is really
helpful,
Really kind of you :)
