### ISSUE TITLE
Is it possible to add a ajax support?

### ISSUE THREAD

**Issue by Quorafind** [HEmile/obsidian-search-on-internet#9]
Why: I did find that some search engine used ajax to do a searching

How: I also searched google for electron support about ajax, here may be some documents or answers you can have a look:
https://stackoverflow.com/questions/9153445/how-to-communicate-between-iframe-and-the-parent-site

I don't know whether iframe allow you create with post request or not, so if it is not possible for making post request when iframing site in ob, please tell me and then I will try other way to achieve my goal. Thanks!

**Comment by HEmile** [comment]
Hi! I'm not very familiar with Ajax. For what site do you need it? And what would need to be added for your use case?
